alter table DDCSR_SCHEDULED_REPORT_CONFIG rename column frequency to frequency__u53982 ;
alter table DDCSR_SCHEDULED_REPORT_CONFIG alter column frequency__u53982 drop not null ;
alter table DDCSR_SCHEDULED_REPORT_CONFIG add column FREQUENCY_MONTHLY_HOUR integer ;
alter table DDCSR_SCHEDULED_REPORT_CONFIG add column FREQUENCY_FREQUENCY varchar(50) ^
update DDCSR_SCHEDULED_REPORT_CONFIG set FREQUENCY_FREQUENCY = 'MONTHLY' where FREQUENCY_FREQUENCY is null ;
alter table DDCSR_SCHEDULED_REPORT_CONFIG alter column FREQUENCY_FREQUENCY set not null ;
alter table DDCSR_SCHEDULED_REPORT_CONFIG add column FREQUENCY_DAILY_MINUTE integer ;
alter table DDCSR_SCHEDULED_REPORT_CONFIG add column FREQUENCY_MONTHLY_DAY integer ;
alter table DDCSR_SCHEDULED_REPORT_CONFIG add column FREQUENCY_CUSTOM_CRON varchar(255) ;
alter table DDCSR_SCHEDULED_REPORT_CONFIG add column FREQUENCY_DAILY_HOUR integer ;
alter table DDCSR_SCHEDULED_REPORT_CONFIG add column FREQUENCY_HOURLY_MINUTE integer ;
